<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Listbarang_model extends CI_Model
{
    public $id = 'no';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get("listbarang")->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get("listbarang")->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no', $q);
	$this->db->or_like('idbarangdibeli', $q);
	$this->db->or_like('idbarang', $q);
	$this->db->or_like('qty', $q);
	$this->db->from("listbarang");
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no', $q);
	$this->db->or_like('idbarangdibeli', $q);
	$this->db->or_like('idbarang', $q);
	$this->db->or_like('qty', $q);
	$this->db->limit($limit, $start);
        return $this->db->get("listbarang")->result();
    }

    // insert data
    function insert($idbarangdibeli, $idbarang, $qty)
    {
		$data["idbarangdibeli"] =  $idbarangdibeli;
		$data["idbarang"] =  $idbarang;
		$data["qty"] =  $qty;

        $this->db->insert("listbarang", $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update("listbarang", $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete("listbarang");
    }

}

/* End of file Listbarang_model.php */
/* Location: ./application/models/Listbarang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-27 08:13:32 */
/* http://harviacode.com */
