<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Proposal_model extends CI_Model
{

    public $id = 'idproposal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
		$this->db->join("user","user.iduser = proposal.idkaryawanpengaju");
        $this->db->order_by($this->id, $this->order);
        $data = $this->db->get("proposal")->result();
		foreach ($data as $key => $value)
		{
			$value->barangList = self::getBarangListbyId($value->idproposal);
		}
		return $data;
    }

    
	function getBarangListbyId($id)
	{
		$this->db->where("idproposal", $id)
		->from("proposalbuylist")
        ->join("barang", "barang.idbarang = proposalbuylist.idbarang")
        ->join("bahanbaku", "bahanbaku.idbahanbaku = barang.idbarang");
		
		return  $this->db->get()->result();
		
	}

	function insertListBarang($idproposal, $idbarang, $qty)
    {
		$data["idproposal"] =  $idproposal;
		$data["idbarang"] =  $idbarang;
		$data["qty"] =  $qty;

        $this->db->insert("proposalbuylist", $data);
    }

	function reject($idproposal)
	{
		$data["status"] = -1;
		$this->db->where("idproposal", $idproposal);
		$this->db->update("proposal", $data);
	}

	function accept($idproposal)
	{
		$data["status"] = 1;
		$this->db->where("idproposal", $idproposal);
		$this->db->update("proposal", $data);
	}
    // insert data
    function insert($data)
    {
        $this->db->insert("proposal", $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update("proposal", $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete("proposal");
    }

}

/* End of file Proposal_model.php */
/* Location: ./application/models/Proposal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-27 08:13:31 */
/* http://harviacode.com */
