<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $id = 'userid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get("user")->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get("user")->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('userid', $q);
		$this->db->or_like('nama', $q);
		$this->db->or_like('email', $q);
		$this->db->or_like('password', $q);
		$this->db->or_like('usertype', $q);
		$this->db->or_like('username', $q);
		$this->db->from("user");
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('userid', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('usertype', $q);
	$this->db->or_like('username', $q);
	$this->db->limit($limit, $start);
        return $this->db->get("user")->result();
    }

    // insert data
    function insert($nama, $email, $password, $usertype, $username)
    {
		$data["nama"] =  $nama				 ;
		$data["email"] =  $email			 ;
		$data["password"] =  $password 		 ;
		$data["usertype"] =  $usertype 		 ;
		$data["username"] =  $username 		 ;
		
		if($usertype != "1" and $usertype != "2") return false;
        $this->db->insert("user", $data);
		$id = $this->db->insert_id();
		if($usertype == "1")
		{
			$manager["idmanager"] = $id;
			$this->db->insert("manager", $manager);
		}
		else  
		{
			$pegawai["idpegawai"] = $id;
			$this->db->insert("pegawai", $pegawai);
		}
		return true;
    }

	function login($username, $password)
	{
		$this->db
		->where("username", $username)
		->where("password", $password);

		return ($this->db->get("user")->num_rows() == 1);
	}

	function isCorrectUserLoggedIn($username)
	{
		$this->db
		->where("username", $username);

		return ($this->db->get("user")->num_rows() == 1);
	}

	function isCorrectUserLoggedInManager($username)
	{
		$this->db
		->where("username", $username)
		->where("role", "0");

		return ($this->db->get("user")->num_rows() == 1);
	}

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update("user", $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete("user");
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-27 08:13:33 */
/* http://harviacode.com */
