<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Manager extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Manager_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'manager/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'manager/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'manager/index.html';
            $config['first_url'] = base_url() . 'manager/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Manager_model->total_rows($q);
        $manager = $this->Manager_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'manager_data' => $manager,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('manager/manager_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Manager_model->get_by_id($id);
        if ($row) {
            $data = array(
		'idmanager' => $row->idmanager,
	    );
            $this->load->view('manager/manager_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('manager'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('manager/create_action'),
	    'idmanager' => set_value('idmanager'),
	);
        $this->load->view('manager/manager_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Manager_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('manager'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Manager_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('manager/update_action'),
		'idmanager' => set_value('idmanager', $row->idmanager),
	    );
            $this->load->view('manager/manager_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('manager'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idmanager', TRUE));
        } else {
            $data = array(
	    );

            $this->Manager_model->update($this->input->post('idmanager', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('manager'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Manager_model->get_by_id($id);

        if ($row) {
            $this->Manager_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('manager'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('manager'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('idmanager', 'idmanager', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Manager.php */
/* Location: ./application/controllers/Manager.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-27 08:13:32 */
/* http://harviacode.com */