<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Proposal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Proposal_model');
		$this->load->model('User_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        self::loginCheck();

        $data["proposal_data"] = $this->Proposal_model->get_all();
        $this->load->view('proposal_view', $data);
    }

    public function accept($id)
	{
		self::loginManagerCheck();

		$this->session->set_flashdata('message', "order diaccept");

        $data["proposal_data"] = $this->Proposal_model->accept($id);
        
		redirect(site_url('Proposal'));
	}

	public function reject($id)
	{
		self::loginManagerCheck();

		$this->session->set_flashdata('message', "order direject");

        $data["proposal_data"] = $this->Proposal_model->reject($id);
        redirect(site_url('Proposal'));
	}

	function loginManagerCheck()
	{
		$username = $this->session->userdata("username");
		if(!$this->User_model->isCorrectUserLoggedInManager($username))
		{
			$this->session->set_flashdata('message', "hanya manager saja");
			redirect(site_url('login'));
		}
	}

	function loginCheck()
	{
		$username = $this->session->userdata("username");
		if(!$this->User_model->isCorrectUserLoggedIn($username))
		{
			$this->session->set_flashdata('message', "anda harus login");
			redirect(site_url('login'));
		}
	}


}

/* End of file Barangdibeli.php */
/* Location: ./application/controllers/Barangdibeli.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-27 08:13:31 */
/* http://harviacode.com */
